[package]
name = "sqlgui-desktop"
version = "0.1.0"
description = "SQL GUI desktop application"
authors = ["bai cie"]
edition = "2021"

[lib]
name = "sqlgui_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"

sqlgui-common = { path = "../../../crates/sqlgui-common" }
sqlgui-db = { path = "../../../crates/sqlgui-db" }
sqlgui-extension = { path = "../../../crates/sqlgui-extension" }
sqlgui-marketplace = { path = "../../../crates/sqlgui-marketplace" }

serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tokio.workspace = true
